import { ConflictException, Injectable } from '@nestjs/common';
import { FinancialDatabase } from './financial.database';
import { FlutterwaveV4PayoutAdapter } from './providers/flutterwave-v4-payout.adapter';
import type { PoolClient } from 'pg';
@Injectable()
export class FinancialPayoutWorker {
  constructor(private readonly database: FinancialDatabase, private readonly provider: FlutterwaveV4PayoutAdapter) {}
  verifyWebhookSignature(raw: Buffer | undefined, signature: string | undefined) { return this.provider.verifyWebhookSignature(raw, signature); }
  async dispatch(payload: Record<string, unknown>) {
    const payoutId=typeof payload.payoutId==='string'?payload.payoutId:'';if(!payoutId)throw Object.assign(new Error('Invalid payout job payload'),{code:'INVALID_PAYLOAD'});
    const row=await this.database.query<any>(`SELECT p.*,d.provider_recipient_id,d.status AS destination_status,d.creator_id AS destination_creator,r.creator_id AS release_creator,r.owner_proceeds_minor,r.currency AS release_currency FROM financial_payout_transfers p JOIN financial_payout_destinations d ON d.id=p.payout_destination_id JOIN financial_campaign_releases r ON r.id=p.release_id WHERE p.id=$1`,[payoutId]);if(!row.rowCount)throw Object.assign(new Error('Payout not found'),{code:'NOT_FOUND'});const p=row.rows[0];
    if(p.state==='paid'||p.provider_transfer_id)return;
    if(p.destination_status!=='verified'||p.destination_creator!==p.creator_id||p.release_creator!==p.creator_id||p.amount_minor!==p.owner_proceeds_minor||p.currency!==p.release_currency)throw Object.assign(new Error('Payout authority validation failed'),{code:'PAYOUT_VALIDATION_FAILED'});
    const transfer=await this.provider.createTransfer({recipientId:p.provider_recipient_id,amountMinor:BigInt(p.amount_minor),currency:p.currency,reference:p.keibo_reference,narration:'KEIBO campaign milestone payout',idempotencyKey:p.idempotency_key});
    const state=transfer.status==='PROCESSING'?'processing':'pending';
    await this.database.transaction(async c=>{await c.query(`UPDATE financial_payout_transfers SET provider_transfer_id=$2,provider_status=$3,state=$4,dispatched_at=now(),updated_at=now() WHERE id=$1 AND provider_transfer_id IS NULL`,[p.id,transfer.id,transfer.status,state]);await this.outbox(c,'payout.dispatched',p.id,{payoutId:p.id,state});await this.schedule(c,p.id);});
  }
  async reconcile(payload:Record<string,unknown>){const payoutId=typeof payload.payoutId==='string'?payload.payoutId:'';if(!payoutId)throw Object.assign(new Error('Invalid payout job payload'),{code:'INVALID_PAYLOAD'});const r=await this.database.query<any>(`SELECT * FROM financial_payout_transfers WHERE id=$1`,[payoutId]);if(!r.rowCount)throw Object.assign(new Error('Payout not found'),{code:'NOT_FOUND'});const p=r.rows[0];if(p.state==='paid')return;if(!p.provider_transfer_id)throw Object.assign(new Error('Transfer dispatch not complete'),{code:'RPC_PENDING'});const result=await this.provider.getTransferStatus(p.provider_transfer_id);await this.database.transaction(async c=>{if(result.status==='SUCCESSFUL'){await c.query(`UPDATE financial_payout_transfers SET state='paid',provider_status=$2,paid_at=now(),updated_at=now() WHERE id=$1 AND state<>'paid'`,[p.id,result.status]);await this.outbox(c,'payout.paid',p.id,{payoutId:p.id});return;}if(result.status==='FAILED'){await c.query(`UPDATE financial_payout_transfers SET state='failed',provider_status=$2,failed_at=now(),updated_at=now() WHERE id=$1 AND state NOT IN ('paid','failed')`,[p.id,result.status]);await this.outbox(c,'payout.failed',p.id,{payoutId:p.id});return;}if(result.status==='UNKNOWN')throw Object.assign(new Error('Provider status unknown'),{code:'RPC_PENDING'});await c.query(`UPDATE financial_payout_transfers SET state=$2,provider_status=$3,updated_at=now() WHERE id=$1 AND state<>'paid'`,[p.id,result.status==='PROCESSING'?'processing':'pending',result.status]);await this.schedule(c,p.id);});}
  async callback(input:{transferId:string;reference:string;amount:string;currency:string;status:'PENDING'|'PROCESSING'|'SUCCESSFUL'|'FAILED'|'UNKNOWN'}){if(!input.transferId||!input.reference||!/^\d+$/.test(input.amount)||input.currency!=='UGX')throw new ConflictException('Malformed payout callback');await this.database.transaction(async c=>{const r=await c.query<any>(`SELECT * FROM financial_payout_transfers WHERE keibo_reference=$1 FOR UPDATE`,[input.reference]);if(!r.rowCount)throw new ConflictException('Unknown payout reference');const p=r.rows[0];if(p.provider_transfer_id!==input.transferId||p.amount_minor!==input.amount||p.currency!==input.currency)throw new ConflictException('Payout callback does not match transfer');if(p.state==='paid')return;if(input.status==='SUCCESSFUL'){await c.query(`UPDATE financial_payout_transfers SET state='paid',provider_status=$2,paid_at=now(),updated_at=now() WHERE id=$1 AND state<>'paid'`,[p.id,input.status]);await this.outbox(c,'payout.paid',p.id,{payoutId:p.id});return;}if(input.status==='FAILED'){await c.query(`UPDATE financial_payout_transfers SET state='failed',provider_status=$2,failed_at=now(),updated_at=now() WHERE id=$1 AND state NOT IN ('paid','failed')`,[p.id,input.status]);await this.outbox(c,'payout.failed',p.id,{payoutId:p.id});return;}if(input.status==='PROCESSING'&&p.state==='pending'){await c.query(`UPDATE financial_payout_transfers SET state='processing',provider_status=$2,updated_at=now() WHERE id=$1`,[p.id,input.status]);await this.outbox(c,'payout.processing',p.id,{payoutId:p.id});}});return{accepted:true};}
  private async schedule(c:PoolClient,payoutId:string){await c.query(`INSERT INTO financial_jobs(job_type,aggregate_type,aggregate_id,deduplication_key,payload,available_at) VALUES ('payout.reconcile.requested','payout_transfer',$1,$2,$3::jsonb,now()+interval '60 seconds') ON CONFLICT(deduplication_key) DO UPDATE SET available_at=LEAST(financial_jobs.available_at,EXCLUDED.available_at)`,[payoutId,`payout.reconcile:${payoutId}`,JSON.stringify({payoutId})]);}
  private async outbox(c:PoolClient,topic:string,id:string,payload:Record<string,unknown>){await c.query(`INSERT INTO financial_outbox(topic,aggregate_id,payload,correlation_id) VALUES($1,$2,$3::jsonb,gen_random_uuid())`,[topic,id,JSON.stringify(payload)]);}
}
