export enum ProjectStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  FUNDING = 'FUNDING',
  FUNDED = 'FUNDED',
  FUNDING_FAILED = 'FUNDING_FAILED',
  CLOSED = 'CLOSED',
}
