export enum UserRole {
  ADMIN = 'ADMIN',
  INNOVATOR = 'INNOVATOR',
  INVESTOR = 'INVESTOR',
  VALIDATOR = 'VALIDATOR',
  ORACLE = 'ORACLE',
}

export enum KYCStatus {
  NOT_VERIFIED = 'NOT_VERIFIED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}
