export enum UserRole {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN',
  INNOVATOR = 'INNOVATOR',
  APPROVER = 'APPROVER',
  INVESTOR = 'INVESTOR',
  TREASURY = 'TREASURY',
}

export enum KYCStatus {
  NOT_VERIFIED = 'NOT_VERIFIED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}
